# Generated by Django 5.2.7 on 2025-10-03 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Full_name', models.CharField(max_length=100)),
                ('image', models.CharField(blank=True, max_length=255, null=True)),
                ('designation', models.TextField()),
                ('facebook_link', models.URLField(blank=True, max_length=300, null=True)),
                ('twitter_link', models.URLField(blank=True, max_length=300, null=True)),
                ('instagram_link', models.URLField(blank=True, max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User_Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Full_name', models.CharField(max_length=100)),
                ('image', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField()),
                ('country', models.CharField(max_length=100)),
            ],
        ),
    ]
