# Generated by Django 5.2.7 on 2025-10-03 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dpps_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_testimonial',
            old_name='country',
            new_name='profession',
        ),
    ]
