# Generated by Django 5.2.7 on 2025-10-14 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dpps_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Full_name', models.CharField(max_length=100)),
                ('image', models.CharField(blank=True, max_length=255, null=True)),
                ('comment', models.TextField()),
                ('profession', models.CharField(max_length=100)),
            ],
        ),
    ]
