# Generated by Django 5.2.7 on 2025-10-14 10:51

import pyuploadcare.dj.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dpps_app', '0002_user_testimonial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_testimonial',
            name='image',
            field=pyuploadcare.dj.models.ImageField(blank=True, null=True),
        ),
    ]
