# Generated by Django 5.2.7 on 2025-10-03 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dpps_app', '0002_rename_country_user_testimonial_profession'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_testimonial',
            old_name='description',
            new_name='comment',
        ),
    ]
