# Generated by Django 5.2.7 on 2025-10-03 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dpps_app', '0003_rename_description_user_testimonial_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('image', models.CharField(blank=True, max_length=255, null=True)),
                ('summary', models.TextField()),
                ('content', models.TextField()),
                ('author', models.CharField(default='DPPS Team', max_length=100)),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
