# Generated by Django 5.2.7 on 2025-10-17 16:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dpps_app', '0004_trainingparticipant'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='Jina Kamili')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Namba ya Simu')),
                ('organization', models.CharField(blank=True, max_length=200, verbose_name='Shirika')),
                ('position', models.CharField(blank=True, max_length=100, verbose_name='Cheo')),
                ('participation_date', models.DateField(verbose_name='Tarehe ya Ushiriki')),
                ('status', models.CharField(choices=[('pending', 'Inasubiri Uthibitisho'), ('approved', 'Imethibitishwa'), ('rejected', 'Imekataliwa')], default='pending', max_length=10)),
                ('certificate', models.URLField(blank=True, verbose_name='Kiungo cha Cheti')),
                ('date_registered', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('training', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dpps_app.training', verbose_name='Mafunzo')),
            ],
            options={
                'verbose_name': 'Mshiriki',
                'verbose_name_plural': 'Washiriki',
            },
        ),
        migrations.DeleteModel(
            name='TrainingParticipant',
        ),
    ]
