# Generated by Django 5.2.7 on 2025-10-17 18:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dpps_app', '0005_training_participant_delete_trainingparticipant'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='participant',
            options={'verbose_name': 'Participant', 'verbose_name_plural': 'Participants'},
        ),
        migrations.AlterField(
            model_name='participant',
            name='certificate',
            field=models.URLField(blank=True, verbose_name='Certificate Link'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='full_name',
            field=models.CharField(max_length=200, verbose_name='Full Name'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='organization',
            field=models.CharField(blank=True, max_length=200, verbose_name='Organization'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='participation_date',
            field=models.DateField(blank=True, verbose_name='Participation Date'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='phone_number',
            field=models.CharField(max_length=20, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='position',
            field=models.CharField(blank=True, max_length=100, verbose_name='Position'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='participant',
            name='training',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dpps_app.training', verbose_name='Training'),
        ),
    ]
