# Generated by Django 5.2.7 on 2025-10-17 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dpps_app', '0006_alter_participant_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='participation_date',
            field=models.DateField(null=True, verbose_name='Participation Date'),
        ),
    ]
