# Generated by Django 5.2.7 on 2025-10-17 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dpps_app', '0007_alter_participant_participation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='participation_date',
            field=models.DateField(blank=True, null=True, verbose_name='Participation Date'),
        ),
    ]
