# Generated by Django 5.2.7 on 2025-10-18 01:16

import pyuploadcare.dj.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dpps_app', '0008_alter_participant_participation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='certificate',
            field=pyuploadcare.dj.models.FileField(blank=True, verbose_name='Certificate File'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
    ]
