# Generated by Django 5.2.7 on 2025-10-18 17:05

import django.core.validators
import pyuploadcare.dj.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dpps_app', '0009_alter_participant_certificate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='certificate',
            field=pyuploadcare.dj.models.FileField(blank=True, null=True, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'docx', 'doc'])], verbose_name='Certificate File'),
        ),
    ]
