"""
Django settings for dpps_project project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-u3g_i2#nvvn*x3-p3vo7f#8ec-bz2*0&1a%f5(%&8q8a08mhtt'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = ["*"]

# Application definition

INSTALLED_APPS = [
        'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'dpps_app'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    "whitenoise.middleware.WhiteNoiseMiddleware",  # hii lazima
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'dpps_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR,'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'dpps_project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }

# supabase database
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'postgres', 
        'USER': 'postgres.usdiowxtnbagijibwind',  
        'PASSWORD': 'NyumbaChap', 
        'HOST': 'aws-1-us-east-2.pooler.supabase.com',  
        'PORT': '5432',  
        "OPTIONS": {
            "options": "-c statement_timeout=60000"  # 60 seconds
        },
    }
}



# user=postgres.usdiowxtnbagijibwind 
# password=[YOUR-PASSWORD] 
# host=aws-1-us-east-2.pooler.supabase.com
# port=5432
# dbname=postgres
# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Location of static files in project
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]


UPLOADCARE = {
    'pub_key': '76122001cca4add87f02',
    'secret': 'f00801b9b65172d50de5',
}
# For production collectstatic
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'








JAZZMIN_SETTINGS = {
    "site_title": "DPPS Ltd | Admin Dashboard",
    "site_header": "Development Project Planning Solution Ltd",
    "site_brand": "DPPS Ltd",
    "welcome_sign": "Welcome to the DPPS Admin Dashboard",
    "copyright": "© 2025 DPPS Ltd",
    
    # Sidebar na navigation
    "show_sidebar": True,
    "navigation_expanded": True,
    "user_avatar": None,
    "search_model": None,  # Hakuna model ya generic

    # Top Menu Links (zimebadilishwa ziendane na kampuni)
    "topmenu_links": [
        {"name": "Home Page", "url": "/", "new_window": True},
        {"name": "About Us", "url": "/about/", "new_window": True},
        {"name": "Services", "url": "/services/", "new_window": True},
        {"name": "Contact", "url": "/contact/", "new_window": True},
    ],

    # Logo na branding
    "site_logo": None,  # Baadaye weka logo URL
    "site_logo_classes": "img-circle",
    "login_logo": None,
    "login_logo_dark": None,

    # Icons kwa app yako
    "icons": {
        "dpps_app.BlogPost": "fas fa-newspaper",
        "dpps_app.User_Testimonial": "fas fa-comment-dots",
        "dpps_app.ContactMessage": "fas fa-envelope",
        "dpps_app.Service": "fas fa-briefcase",
    },
}

JAZZMIN_UI_TWEAKS = {
    "theme": "flatly",       # safi na ya kisasa
    "navbar_fixed": True,
    "sidebar_fixed": True,
    "footer_fixed": False,
    "show_ui_builder": False,
    "brand_colour": "navbar-primary",  # rangi ya primary ya company
    "dark_mode_theme": "darkly",       # optional dark mode
}
